FROM node:20
WORKDIR /app
COPY ./Isla/package*.json ./
RUN npm install -g @angular/cli && npm install
COPY ./Isla/ .
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll=2000"]